version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: S3cureDbPass987
      MYSQL_DATABASE: ms-performance
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pS3cureDbPass987"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

