export const products = [
  {
    id: 1,
    title: "Uprated Throttle Actuators - BMW E90 | E92 | E93 M3 (PAIR)",
    price: "£770.00",
    oldPrice: "£890.00",
    rating: 4.5,
    discount: null,
    image: "/images/products/product1.png",
    sold: 1238,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    specification: "High-quality throttle actuators designed for BMW M3 models.",
  },
  {
    id: 2,
    title: "Uprated Throttle Actuators - BMW E90 | E92 | E93 M3 (PAIR)",
    price: "£155",
    oldPrice: null,
    rating: 3.5,
    discount: null,
    image: "/images/products/product2.png",
    sold: 856,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    specification: "Premium performance upgrade for your vehicle.",
  },
  {
    id: 3,
    title: "Uprated Throttle Actuators - BMW E90 | E92 | E93 M3 (PAIR)",
    price: "£190",
    oldPrice: null,
    rating: 4.5,
    discount: null,
    image: "/images/products/product3.png",
    sold: 642,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    specification: "Engineered for maximum performance and reliability.",
  },
  {
    id: 4,
    title: "Uprated Throttle Actuators - BMW E90 | E92 | E93 M3 (PAIR)",
    price: "£130",
    oldPrice: "£160",
    rating: 5,
    discount: "-30%",
    image: "/images/products/product4.png",
    sold: 2341,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    specification: "Professional grade automotive components.",
  },
];

