"""improve_schema_add_fields

Revision ID: 1329b415c750
Revises: 198bd78f89a3
Create Date: 2025-12-02 04:08:19.391447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1329b415c750'
down_revision: Union[str, None] = '198bd78f89a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_id'), ['id'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('category_slug',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'category', ['parent_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.alter_column('product_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sale_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_order_status'), ['order_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_payment_status'), ['payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payment_status'))
        batch_op.drop_index(batch_op.f('ix_sale_order_status'))
        batch_op.drop_index(batch_op.f('ix_sale_order_number'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('tax')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('order_status')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('weight')
        batch_op.drop_column('image_url')
        batch_op.drop_column('sku')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('category_slug',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('category_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_id'))

    op.drop_table('address')
    # ### end Alembic commands ###
