"""add tax system

Revision ID: a1b2c3d4e5f6
Revises: d05ff20d29a9
Create Date: 2025-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'b83b2f8d08ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if tables exist before creating (for partial migrations)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create tax_class table
    if 'tax_class' not in existing_tables:
        op.create_table('tax_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_class_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_class_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tax_class_slug'), ['slug'], unique=True)
    
    # Create tax_rate table
    if 'tax_rate' not in existing_tables:
        op.create_table('tax_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('state_code', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('compound', sa.Boolean(), nullable=False),
    sa.Column('shipping', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['tax_class_id'], ['tax_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rate_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rate_tax_class_id'), ['tax_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rate_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rate_state_code'), ['state_code'], unique=False)
    
    # Add tax fields to product table (check if columns exist first)
    inspector = inspect(conn)
    product_columns = [col['name'] for col in inspector.get_columns('product')]
    
    with op.batch_alter_table('product', schema=None) as batch_op:
        if 'tax_class_id' not in product_columns:
            batch_op.add_column(sa.Column('tax_class_id', sa.Integer(), nullable=True))
        if 'tax_status' not in product_columns:
            batch_op.add_column(sa.Column('tax_status', sa.String(length=20), nullable=False, server_default='taxable'))
        # Check if foreign key exists
        fk_exists = any(
            fk['name'] == 'fk_product_tax_class' 
            for fk in inspector.get_foreign_keys('product')
        )
        if not fk_exists and 'tax_class_id' in product_columns:
            batch_op.create_foreign_key('fk_product_tax_class', 'tax_class', ['tax_class_id'], ['id'])
        # Check if index exists
        indexes = [idx['name'] for idx in inspector.get_indexes('product')]
        if 'ix_product_tax_class_id' not in indexes and 'tax_class_id' in product_columns:
            batch_op.create_index(batch_op.f('ix_product_tax_class_id'), ['tax_class_id'], unique=False)
    
    # Update sale table - add subtotal and shipping_tax, modify tax field
    sale_columns = [col['name'] for col in inspector.get_columns('sale')]
    
    with op.batch_alter_table('sale', schema=None) as batch_op:
        # Add subtotal column (before tax) - nullable first
        if 'subtotal' not in sale_columns:
            batch_op.add_column(sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True))
        # Add shipping_tax column
        if 'shipping_tax' not in sale_columns:
            batch_op.add_column(sa.Column('shipping_tax', sa.DECIMAL(precision=10, scale=2), nullable=True))
    
    # Migrate existing data: set subtotal = total_amount - tax - shipping_cost
    # This is a safe migration for existing data (do this outside batch_alter)
    if 'subtotal' in [col['name'] for col in inspector.get_columns('sale')]:
        op.execute("""
            UPDATE sale 
            SET subtotal = COALESCE(total_amount, 0) - COALESCE(tax, 0) - COALESCE(shipping_cost, 0)
            WHERE subtotal IS NULL
        """)
    
    # Now make subtotal NOT NULL and update tax column
    sale_columns_after = [col['name'] for col in inspector.get_columns('sale')]
    with op.batch_alter_table('sale', schema=None) as batch_op:
        # Set subtotal to NOT NULL after data migration
        if 'subtotal' in sale_columns_after:
            # Check if it's already NOT NULL
            subtotal_col = next((col for col in inspector.get_columns('sale') if col['name'] == 'subtotal'), None)
            if subtotal_col and subtotal_col.get('nullable', True):
                batch_op.alter_column('subtotal', nullable=False)
        if 'shipping_tax' in sale_columns_after:
            batch_op.alter_column('shipping_tax', nullable=True, server_default='0.00')
        # Update existing tax column to be NOT NULL with default 0
        tax_col = next((col for col in inspector.get_columns('sale') if col['name'] == 'tax'), None)
        if tax_col and tax_col.get('nullable', True):
            batch_op.alter_column('tax', 
                                 existing_type=sa.DECIMAL(precision=10, scale=2),
                                 nullable=False,
                                 server_default='0.00')
        # Reorder columns for better organization (optional, but cleaner)
        # Note: SQLite doesn't support column reordering, so we'll keep the order as is
    
    # Update sale_item table - add tax fields
    sale_item_columns = [col['name'] for col in inspector.get_columns('sale_item')]
    
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        if 'tax_rate' not in sale_item_columns:
            batch_op.add_column(sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=4), nullable=True))
        if 'tax_amount' not in sale_item_columns:
            batch_op.add_column(sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00'))
        if 'line_total' not in sale_item_columns:
            batch_op.add_column(sa.Column('line_total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    
    # Migrate existing data: set line_total = quantity * price_per_unit (no tax for old records)
    sale_item_columns_after = [col['name'] for col in inspector.get_columns('sale_item')]
    if 'line_total' in sale_item_columns_after:
        op.execute("""
            UPDATE sale_item 
            SET line_total = quantity * price_per_unit,
                tax_rate = 0.0000,
                tax_amount = 0.00
            WHERE line_total IS NULL
        """)
    
    # Set line_total to NOT NULL after data migration
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        if 'line_total' in sale_item_columns_after:
            line_total_col = next((col for col in inspector.get_columns('sale_item') if col['name'] == 'line_total'), None)
            if line_total_col and line_total_col.get('nullable', True):
                batch_op.alter_column('line_total', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove tax fields from sale_item
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_column('line_total')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')
    
    # Remove tax fields from sale
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('shipping_tax')
        batch_op.drop_column('subtotal')
        batch_op.alter_column('tax', nullable=True)
    
    # Remove tax fields from product
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tax_class_id'))
        batch_op.drop_constraint('fk_product_tax_class', type_='foreignkey')
        batch_op.drop_column('tax_status')
        batch_op.drop_column('tax_class_id')
    
    # Drop tax_rate table
    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rate_state_code'))
        batch_op.drop_index(batch_op.f('ix_tax_rate_country_code'))
        batch_op.drop_index(batch_op.f('ix_tax_rate_tax_class_id'))
        batch_op.drop_index(batch_op.f('ix_tax_rate_id'))
    
    op.drop_table('tax_rate')
    
    # Drop tax_class table
    with op.batch_alter_table('tax_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_class_slug'))
        batch_op.drop_index(batch_op.f('ix_tax_class_name'))
        batch_op.drop_index(batch_op.f('ix_tax_class_id'))
    
    op.drop_table('tax_class')
    # ### end Alembic commands ###

