"""create_settings_table

Revision ID: a53d55602b7e
Revises: add_appointment_tables
Create Date: 2026-01-23 18:19:39.935192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a53d55602b7e'
down_revision: Union[str, None] = 'add_appointment_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))

    with op.batch_alter_table('shop_hours', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0=Monday, 6=Sunday',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_shop_hours_day_of_week'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_hours_day_of_week'), ['day_of_week'], unique=False)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.INTEGER(),
               comment='0=Monday, 6=Sunday',
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)

    # ### end Alembic commands ###
