"""enhance_products_woocommerce_features

Revision ID: b83b2f8d08ee
Revises: d05ff20d29a9
Create Date: 2025-12-02 17:15:37.256912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b83b2f8d08ee'
down_revision: Union[str, None] = 'd05ff20d29a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sale_start_date', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('sale_end_date', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_virtual', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_downloadable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stock_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('manage_stock', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stock_threshold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backorders_allowed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('width', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('height', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shipping_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shipping_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('shipping_taxable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('purchase_note', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('enable_reviews', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('upsell_ids', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cross_sell_ids', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('button_text', sa.String(length=100), nullable=True))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_product_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key('fk_product_parent_id', 'product', ['parent_id'], ['id'])

    # Create new tables for WooCommerce features
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_product_id'), ['product_id'], unique=False)

    op.create_table('product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attribute_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_attribute_slug'), ['slug'], unique=True)

    op.create_table('product_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('display_value', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_attribute.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_attribute_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attribute_value_attribute_id'), ['attribute_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.String(length=20), nullable=False),
    sa.Column('manage_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_threshold', sa.Integer(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('length', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_sku'), ['sku'], unique=True)

    op.create_table('product_variant_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['product_attribute_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_attribute_variant_id'), ['variant_id'], unique=False)

    op.create_table('product_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tag_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_tag_slug'), ['slug'], unique=True)

    op.create_table('product_tag_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['product_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_tag_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tag_relation_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_tag_relation_tag_id'), ['tag_id'], unique=False)

    op.create_table('product_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('reviewer_email', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_review_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_review_user_id'), ['user_id'], unique=False)

    op.create_table('product_category_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_category_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_relation_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_relation_category_id'), ['category_id'], unique=False)

    # Set default values for new columns
    op.execute("UPDATE product SET product_type = 'simple' WHERE product_type IS NULL")
    op.execute("UPDATE product SET stock_status = 'in_stock' WHERE stock_status IS NULL")
    op.execute("UPDATE product SET status = 'published' WHERE status IS NULL")
    op.execute("UPDATE product SET is_virtual = 0 WHERE is_virtual IS NULL")
    op.execute("UPDATE product SET is_downloadable = 0 WHERE is_downloadable IS NULL")
    op.execute("UPDATE product SET manage_stock = 1 WHERE manage_stock IS NULL")
    op.execute("UPDATE product SET backorders_allowed = 0 WHERE backorders_allowed IS NULL")
    op.execute("UPDATE product SET shipping_required = 1 WHERE shipping_required IS NULL")
    op.execute("UPDATE product SET shipping_taxable = 1 WHERE shipping_taxable IS NULL")
    op.execute("UPDATE product SET is_featured = 0 WHERE is_featured IS NULL")
    op.execute("UPDATE product SET enable_reviews = 1 WHERE enable_reviews IS NULL")
    op.execute("UPDATE product SET review_count = 0 WHERE review_count IS NULL")
    op.execute("UPDATE product SET average_rating = 0 WHERE average_rating IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new tables
    op.drop_table('product_category_relation')
    op.drop_table('product_review')
    op.drop_table('product_tag_relation')
    op.drop_table('product_tag')
    op.drop_table('product_variant_attribute')
    op.drop_table('product_variant')
    op.drop_table('product_attribute_value')
    op.drop_table('product_attribute')
    op.drop_table('product_image')
    
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_parent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_product_slug'))
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('button_text')
        batch_op.drop_column('external_url')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('cross_sell_ids')
        batch_op.drop_column('upsell_ids')
        batch_op.drop_column('review_count')
        batch_op.drop_column('average_rating')
        batch_op.drop_column('enable_reviews')
        batch_op.drop_column('purchase_note')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('status')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('shipping_taxable')
        batch_op.drop_column('shipping_required')
        batch_op.drop_column('shipping_class')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')
        batch_op.drop_column('backorders_allowed')
        batch_op.drop_column('stock_threshold')
        batch_op.drop_column('manage_stock')
        batch_op.drop_column('stock_status')
        batch_op.drop_column('is_downloadable')
        batch_op.drop_column('is_virtual')
        batch_op.drop_column('product_type')
        batch_op.drop_column('sale_end_date')
        batch_op.drop_column('sale_start_date')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('short_description')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
