"""create_missing_tables_settings_services

Revision ID: c87ae59e0cfb
Revises: df2cba6da5a0
Create Date: 2026-01-23 18:28:13.307715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87ae59e0cfb'
down_revision: Union[str, None] = 'df2cba6da5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_title'), ['title'], unique=True)

    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_key'), ['key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_key'))

    op.drop_table('setting')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_title'))
        batch_op.drop_index(batch_op.f('ix_service_id'))

    op.drop_table('service')
    # ### end Alembic commands ###
