"""Add contact message table

Revision ID: f7bb11c22fa4
Revises: 78130ca33269
Create Date: 2025-12-26 00:02:02.898931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f7bb11c22fa4'
down_revision: Union[str, None] = '78130ca33269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_id'), ['id'], unique=False)

    with op.batch_alter_table('product_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attribute_id'), ['id'], unique=False)

    with op.batch_alter_table('product_attribute_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attribute_value_id'), ['id'], unique=False)

    with op.batch_alter_table('product_category_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category_relation_id'), ['id'], unique=False)

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_id'), ['id'], unique=False)

    with op.batch_alter_table('product_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_review_id'), ['id'], unique=False)

    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tag_id'), ['id'], unique=False)

    with op.batch_alter_table('product_tag_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tag_relation_id'), ['id'], unique=False)

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_id'), ['id'], unique=False)

    with op.batch_alter_table('product_variant_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_attribute_id'), ['id'], unique=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('tax',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('tax',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('product_variant_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_attribute_id'))

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_id'))

    with op.batch_alter_table('product_tag_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tag_relation_id'))

    with op.batch_alter_table('product_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tag_id'))

    with op.batch_alter_table('product_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_review_id'))

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_id'))

    with op.batch_alter_table('product_category_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_relation_id'))

    with op.batch_alter_table('product_attribute_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attribute_value_id'))

    with op.batch_alter_table('product_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attribute_id'))

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_id'))
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))

    op.drop_table('contact_message')
    # ### end Alembic commands ###
